<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>LPH_2._0</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SocketIOClient" Version="3.1.2" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.11" />
    <PackageReference Include="System.IO.Ports" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ModemAPI">
      <HintPath>..\..\ModemAPI\bin\Debug\net9.0\ModemAPI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>